collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1301003
  brandStrength: 1
  lightness: 0.7629576
  brandColors:
    - '#FFFFFF'
    - '#020202'
    - '#303030'
    - '#5C5C5C'
    - '#888888'
  rhythmicContrast: 0.2873226
typography_spectrum: 0.4266442
layout_spectrum: 0.2099494
name: GoingPDX
